
title: Eric's C V
url: 'http://junlulocky.com'
baseurl: '/my-resume ' #change it according to your repository name


# Profile information
yourname: Rabemampiandra Eric Noel  ## put your name
title: 'Electronic Engineer & Huawei Core Network & AI, Data Science, full stack Dev'  ## your title
location: Antananarivo, Madagascar


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
